name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    uses: Staffbase/gha-workflows/.github/workflows/template_release_drafter.yml@v7.9.0
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
